package org.firstinspires.ftc.teamcode.common;

// Used to manage all mechanisms except drivetrain
public enum Modes {
    AUTO_START_POS,
    AUTO_END_POS,
    TELEOP_START_POS,
    CRUISING,
    INTAKE_HOVER_POS,
    INTAKE_BRICK_FOR_HANDOFF,
    INTAKE_BRICK_SIMPLE,
    HANDLER_HANDOFF_PREP_POS,
    HANDLER_GRAB_SPECIMEN_POS,
    HAND_OFF_BRICK,
    TELEOP_HANDOFF,
    LOOKING_POS,
    NOT_LOOKING_POS,
    TELEOP_GRAB_SPECIMEN,
    GRAB_SPECIMEN,
    HANDLER_HIGH_BUCKET_POS,
    HANDLER_HIGH_SPECIMEN_POS,
    HANG_SPECIMEN,
    PARKING_AT_SUB_POS;
}

