{"startPoint":{"x":55.2,"y":8.3,"heading":"linear","startDeg":90,"endDeg":180},
"lines":[
{"name":"S1B1 Pickup","endPoint":{"x":40,"y":36,"heading":"linear","startDeg":90,"endDeg":180},"controlPoints":[],"color":"#79A58C"},
{"name":"S1B1 Shoot","endPoint":{"x":72,"y":24,"heading":"linear","reverse":false,"startDeg":180,"endDeg":60,"degrees":90},"controlPoints":[],"color":"#55955B"},
{"name":"S1B2 Pickup","endPoint":{"x":36,"y":36,"heading":"linear","reverse":false,"startDeg":60,"endDeg":180},"controlPoints":[],"color":"#6685CD"},
{"name":"S1B2 Shoot","endPoint":{"x":72,"y":24,"heading":"linear","reverse":false,"startDeg":180,"endDeg":60},"controlPoints":[],"color":"#C9BA7B"},
{"name":"S1B3 Pickup","endPoint":{"x":30,"y":36,"heading":"linear","reverse":false,"startDeg":60,"endDeg":180},"controlPoints":[],"color":"#56798A"},
{"name":"S1B3 Shoot","endPoint":{"x":72,"y":24,"heading":"linear","reverse":false,"startDeg":180,"endDeg":60},"controlPoints":[],"color":"#9C9A57"},
{"name":"S2B1 Pickup","endPoint":{"x":40,"y":60,"heading":"linear","reverse":false,"startDeg":60,"endDeg":180},"controlPoints":[],"color":"#7B97CD"},
{"name":"S2B1 Shoot","endPoint":{"x":72,"y":72,"heading":"linear","reverse":false,"startDeg":180,"endDeg":45},"controlPoints":[],"color":"#5C86CD"},
{"name":"S2B2 Pickup","endPoint":{"x":36,"y":60,"heading":"linear","reverse":false,"startDeg":45,"endDeg":180},"controlPoints":[],"color":"#7BA77B"},
{"name":"S2B2 Shoot","endPoint":{"x":72,"y":72,"heading":"linear","reverse":false,"startDeg":180,"endDeg":45},"controlPoints":[],"color":"#C69BC8"},
{"name":"S2B3 Pickup","endPoint":{"x":30,"y":60,"heading":"linear","reverse":false,"startDeg":45,"endDeg":180},"controlPoints":[],"color":"#9659AB"},
{"name":"S2B3 Shoot","endPoint":{"x":72,"y":72,"heading":"linear","reverse":false,"startDeg":180,"endDeg":45},"controlPoints":[],"color":"#A9D967"},
{"name":"S3B1 Pickup","endPoint":{"x":40,"y":84,"heading":"linear","reverse":false,"startDeg":45,"endDeg":180},"controlPoints":[],"color":"#5867AD"},
{"name":"S3B1 Shoot","endPoint":{"x":72,"y":72,"heading":"linear","reverse":false,"startDeg":180,"endDeg":45},"controlPoints":[],"color":"#D6CA8D"},
{"name":"S3B2 Pickup","endPoint":{"x":36,"y":84,"heading":"linear","reverse":false,"startDeg":45,"endDeg":180},"controlPoints":[],"color":"#C58CC6"},
{"name":"S3B2 Shoot","endPoint":{"x":72,"y":72,"heading":"linear","reverse":false,"startDeg":180,"endDeg":45},"controlPoints":[],"color":"#7D5AAB"},
{"name":"S3B3 Pickup","endPoint":{"x":30,"y":84,"heading":"linear","reverse":false,"startDeg":45,"endDeg":180},"controlPoints":[],"color":"#B8C5DB"},
{"name":"S3B3 Shoot","endPoint":{"x":72,"y":72,"heading":"linear","reverse":false,"startDeg":180,"endDeg":45},"controlPoints":[],"color":"#95C7CC"},
{"name":"Park","endPoint":{"x":38.7,"y":33.2,"heading":"linear","reverse":false,"startDeg":45,"endDeg":90},"controlPoints":[],"color":"#965596"}],"shapes":[]}